### ISSUE TITLE
How to run ios provider on the same machine with STF server?

### ISSUE THREAD

**Issue by viktorgogulenko** [tmobile/stf_ios_support#1] opened 2019-11-25 09:17 UTC
Hi. I was going through your readme file to start ios provider and for me little bit not clear how to run it on the same machine with STF server - for example I have Mac Mini with STF server and want to run ios provider there as well. Is it possible? And for me not clear for what reasons to use VPN connection and have this complexity?
Also where should I find yaml-file for 'docker-compose up -d' command as seems it's not in repo or I've missed something?
Thanks a lot in advance for any help as I'm really want to try your solution!

**Comment by nanoscopic** [comment] 2019-12-04 19:05
The updates yesterday allow the coordinator to now be used without a VPN setup. Before those updates VPN had to be used.

You do still need to specify the network interface to be used so that the coordinator knows how to identify itself to the STF server.

It should now be possible to have both STF server and Provider on the same machine, despite being an unusual setup. It is reasonable for testing. I have not yet tried having everything running on one machine yet though.

**Comment by nanoscopic** [comment] 2019-12-04 19:45
The server folder now contains example docker-compose.yml, some needed files to go with it, and some basic instructions. https://github.com/tmobile/stf_ios_support/tree/master/server

Will leave this issue open for you to post other issues / questions you have getting it up and running to ensure what is needed to get it up is there and the instructions are adequate.

**Comment by cesar-montoya** [comment] 2019-12-06 20:06
@nanoscopic hi again! I am following this thread, and I am having issues as well.  When I execute docker-compose up I am getting the below error:

```
qa@QA-MacBook-Pro QA % docker-compose up 
Creating network "qa_default" with the default driver
Creating volume "qa_rethinkdb" with default driver
Creating volume "qa_storage-temp" with default driver
Building storage-temp
ERROR: Cannot locate specified Dockerfile: Dockerfile
```

**Comment by nanoscopic** [comment] 2019-12-09 22:33
You must first follow the main stf_ios_support instructions for setting up a server to build the 'stf_with_ios:1.0' image. That is, you need to do `make docker` in the root of the stf_ios_support folder to create the docker image first. If you do that on a different machine than where you are doing `docker-compose up`, then you will need to transfer the image to that machine.

You can also use any standard STF server image. The standard STF Dockerfile that ultimately builds an image is in the STF repo: https://github.com/openstf/stf/blob/master/Dockerfile

For the stf_ios_support repo, the Dockerfile used for STF is this one: https://github.com/tmobile/stf/blob/ios-support/Dockerfile It is different from the upstream in that it has been cleaned up a bit and moved to Ubuntu 18 and Node 8. Upstream uses Ubuntu 16 and Node 6.

**Comment by Bull3time** [comment] 2020-01-01 05:37
First up great work this project shows heaps of promise! Hopefully the openstf devs give you some guidance on a way forward to merge this in with the main project.

A couple of issues I've had;

1. I'm having problems with the wdaproxy, I can start it manually with `./wdaproxy -p 8100 -u $(idevice_id -l)` and control my iPhone via the url it prints, but if I run it inside the stf_ios_support with `./run` it doesn't work, also the new wda_wrapper you just committed also fails and loops 

```
INFO[0000] wda wrapper started                           iosVersion= proc=wda_wrapper type=proc_start uuid= wdaPort=8100 wdaRoot=
INFO[0000]                                               args="[-p 8100 -q 8100 -d -W . -u  --iosversion=]" cmd=../wdaproxy type=proc_cmdline
ERRO[0000]                                               line="2020/01/01 16:12:56 main.go:136 freeport 64358" type=proc_stderr
ERRO[0000]                                               line="2020/01/01 16:12:56 main.go:139 launch tcp-proxy, listen on 8100" type=proc_stderr
ERRO[0000]                                               line="2020/01/01 16:12:56 main.go:235 Open webbrower with http://x.x.x.x:8100" type=proc_stderr
ERRO[0000]                                               line="2020/01/01 16:12:56 main.go:146 launch iproxy (udid: \"XXXXXXXX-XXXXXXXXX\")" type=proc_stderr
ERRO[0000]                                               line="2020/01/01 16:12:56 main.go:161 device name: iPhone" type=proc_stderr
ERRO[0000]                                               line="2020/01/01 16:12:56 main.go:163 launch WebDriverAgent(dir=.)" type=proc_stderr
ERRO[0000]                                               line="2020/01/01 16:12:56 main.go:175 Could not find WebDriverAgent.xcodeproj or xctestrun of sufficient version" type=proc_stderr
INFO[0000] Wdaproxy ended                                type=proc_end
```

Here is the working output from wdaproxy
```
:wdaproxy user$ ./wdaproxy -p 8100 -u $(idevice_id -l)
2020/01/01 16:01:20 main.go:136 freeport 63728
2020/01/01 16:01:20 main.go:139 launch tcp-proxy, listen on 8100
2020/01/01 16:01:20 main.go:146 launch iproxy (udid: "XXXXXXXX-XXXXXXXXX")
2020/01/01 16:01:20 main.go:235 Open webbrower with http://x.x.x.x:8100
[16:01:25] 200 GET /remote (x.x.x.x) 1.33ms
```

Here is the logs from running the coordinator that do not work
```
2020/01/01 16:01:20 main.go:136 freeport 63725
2020/01/01 16:01:20 main.go:139 launch tcp-proxy, listen on 8100
2020/01/01 16:01:20 main.go:235 Open webbrower with http://x.x.x.x8100
2020/01/01 16:01:20 main.go:146 launch iproxy (udid: "XXXXXXXX-XXXXXXXXX")
2020/01/01 16:01:20 main.go:161 device name: 
2020/01/01 16:01:20 main.go:163 launch WebDriverAgent(dir=.)
2020/01/01 16:01:20 main.go:175 Could not find WebDriverAgent.xcodeproj or xctestrun of sufficient version
```

2. I kept getting wda_wrapper failing to start as it was looking for the wrong path, tried modifying it and removed the ../ but that didn't work (i don't know go), so moved a copy of the wdaproxy one directory up
```
INFO[0000] wda wrapper started                           iosVersion= proc=wda_wrapper type=proc_start uuid= wdaPort=8100 wdaRoot=
INFO[0000]                                               args="[-p 8100 -q 8100 -d -W . -u  --iosversion=]" cmd=../wdaproxy type=proc_cmdline
ERRO[0000] Error starting wdaproxy                       error="fork/exec ../wdaproxy: no such file or directory" type=proc_err
```

3. I also had to `make docker` inside `repos/stf`, just as an fyi

Any help would be appreciated, keen to get this running on the one mac, I have had a few docker-compose issues as well but so far worked around them, specifically for the nginx service getting 443 to bind to 127.0.0.1 otherwise the token forwarding wouldn't work in stf (even with nginx header rewriteness) 
```
ports:
      - 80:80
      - "127.0.0.1:443:443"
```

Regards.

**Comment by nanoscopic** [comment] 2020-01-01 20:10
@Bull3time In the logs you show, iosVersion is not set. I noticed this happening as well during development, and did shift the version detection code in coordinator around a bit to resolve it. That seems to have worked for me, but is not working on your setup. The only reason it is required right now is due to the way I changed the wdaproxy itself. I will make further changes today to remove the requirement so it works even when iosVersion ends up blank.

Note also in your shown log, both uuid and wdaRoot are both blank on the 'wda wrapper started' line. Without those set it won't work; have you altered the output here to hide those values? If the system isn't detecting that your IOS device is plugged in, and fetching its uuid; that would also lead to iosVersion not being set. It is possible it is a timing issue related to video activation causing the IOS device connection to drop and re-appear. Could you try with 'skip_video' set to true in config? If that lets wdaproxy start properly then it is a timing issue related to the video.

wda_wrapper is built into the `stf_ios_support/bin/wda_wrapper` location
wda itself is in a folder `stf_ios_support/bin/wda/[wda files]`
The current working directory of wda_wrapper is set to be the same directory that the coordinator was started from. That directory does need to be the stf_ios_support folder if run locally ( not using a deployed dist.tgz )
Then, in turn, the wda_folder is set by default to bin 'bin/wda'. So; when wda_wrapper is started by plist, it should set the working directory of wdaproxy to be 'stf_ios_support/bin/wda' ( via this line: https://github.com/tmobile/stf_ios_support/blob/master/wda_wrapper/wda_wrapper.go#L69 )

Since wdaproxy then is run from stf_ios_support/bin/wda/, ../wdaproxy should be found at stf_ios_support/bin/wdaproxy

Initially when I was testing this I hardcoded the paths specific to my machine. I changed them before commit to relative paths sourced from config ( with defaults in coordinator/config.go ). I will test again; I may have missed something minor about the paths.

All of the development and testing is being done with an active VPN connection using Tunnelblick; the port binding issue is a result of not thoroughly testing running everything with the VPN off. You likely need to grant permission in the Preferences->Firewall on MacOS to allow docker to bind to the lower port range.

**Comment by Bull3time** [comment] 2020-01-02 01:09
I've made some progress; Your mention of the missing ios version seemed odd since I have seen other logs where it finds the version, detects the uuid etc. I then tried running the wda_wrapper manually and getting that to run. Running with `./wda_wrapper -wdaRoot ./wda/ -uuid 00008020-001D58361E08002E -iosVersion=13.3` i noticed for some reason in `bin/wda/`that the xctestrun file was named incorrectly for my iOS version. Simply changing it to match 13.3 has made wdaproxy and the wda_wrapper to start properly `cp WebDriverAgentRunner_iphoneos13.2-arm64e.xctestrun WebDriverAgentRunner_iphoneos13.3-arm64e.xctestrun`

Stf seems to be able to communicate somewhat to the device now but video isn't working, I've found some logs about self signed certificates so I'll dig into that and should hopefully get it working.

OSX firewall doesn't have any special permissions I can set for Docker, but the setup I've got atm is working ok (hopefully the video streaming is just the self signed certificate which I should be able to tell something to be happy with) and it should all be good then.

Will let you know if I get video working.

**Comment by nanoscopic** [comment] 2020-01-02 06:58
The changes I made to wdaproxy are to "insist" that the name of the xctestrun file is equal to or greater than the version of the OS you are running against. While it may be possible to run a version of the WDA built against a lower version, it is not guaranteed to work. I would recommend that you update your version of Xcode and rebuild; which should increase the numbered version of the WDA build.

I have additional seen cases where there will be two different xctestrun files in the built WDA folder with two different version numbers. Rebuilding WDA from scratch I cannot replicate that happening but I have had it happen and the changes to wdaproxy do support selecting the proper xctestrun file.

With the new changes / current version of stf_ios_support; it should be alright to run the wda_wrapper manually, as it is now essentially detached from the coordinator itself. It sends data to the coordinator through a ZeroMQ push port.

The video needs several things to work:
1. The "video enabler" needs to be running; since that doesn't need any specific UUID to run, I would guess it is running when you start the coordinator without issue.
2. The named pipe must be created properly. This is likely fine also. They are created in the stf_ios_support/video_pipes folder. The first one to be used if you connect just one device is 'pipe_8000'
3. Ffmpeg must start up properly and not error out. You can view the log of ffmpeg after starting the coordinator using `./view_log -proc ffmpeg` from within the stf_ios_support folder.
4. MirrorFeed must start up properly. I don't think this will have a problem as it is one of the most stable components so far. You can though view the log of it with `./view_log -proc mirrorfeed`

If you want to simply test that your MacOS machine is able to receive video from your IOS device, you should open Quicktime Player, select File -> New Movie Recording, then click the arrow dropdown next to the record icon in the center of the screen and select the name of your IOS device. That will display live video from your IOS device on screen. If that works, then typically FFmpeg will start up and work properly along with MirrorFeed.

The video working that way assumes you have started the coordinator yourself in a terminal window. ( not through a plist or using the created App ) When run this way you will be prompted to give the Terminal you started the coordinator under permission to get the video from the phone.

We currently have proven out getting video to work via the built app, but it requires additional steps that will soon be added into the stf_ios_support repo. ( signing the app ) If you set your config correctly, build the app, then sign the app, you can then start the coordinator by double clicking the app itself.... I'd recommend waiting till that information is added into the repo itself though as signing will be integrated and additional documentation added.

**Comment by Bull3time** [comment] 2020-01-02 11:51
Yeah my guess is my version of Xcode thinks 13.2 is the latest and getting the latest Xcode plus a rebuild would fix that up.

Thanks for the tip on opening quicktime, I can confirm that it is happily playing a video stream from the device. I suspect it's to do with openstf actually being able to route back to the video stream as console shows `[Error] WebSocket connection to 'wss://macbook-pro-3.local/frames/fd7b:8e4a:f5b3:0:75cd:b259:b214:5c91/8000/x' failed: Unexpected response code: 500` along with nginx errors 

```nginx_1                 | 2020/01/02 09:35:25 [error] 6#6: *82 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.16.1, server: _, request: "GET /frames/127.94.0.1/8000/x HTTP/1.1", upstream: "http://127.94.0.1:8000/echo/", host: "macbook-pro-3.local"
nginx_1                 | 192.168.16.1 - - [02/Jan/2020:09:35:25 +0000] "GET /frames/127.94.0.1/8000/x HTTP/1.1" 502 150 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Safari/605.1.15"
nginx_1                 | 2020/01/02 09:35:47 [error] 6#6: *85 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.16.1, server: _, request: "GET /frames/127.94.0.1/8000/x HTTP/1.1", upstream: "http://127.94.0.1:8000/echo/", host: "127.0.0.1"
```

If i browse `wss://127.0.0.1/frames/127.94.0.1/8000/x` directly it still throws errors so unsure where to go from here.

**Comment by Bull3time** [comment] 2020-01-02 23:25
I've tried the solution here https://serverfault.com/questions/317393/connect-failed-111-connection-refused-while-connecting-to-upstream, but that hasn't worked, also switching from en0 to lo0 took it from ipv6 back to ipv4 which I thought was the root of the issue but that hasn't worked either. I think it's that address isn't routable, aka the second address in the wss url. What sets up this redirect?

**Comment by nanoscopic** [comment] 2020-01-03 05:10
The websocket URL is formed by using the 'stf_hostname' option within config.json. This line of code is what sets it: https://github.com/tmobile/stf_ios_support/blob/b065244ca0a5623e361dbaea9ce7eea6d8bc7f82/coordinator/proc_device_unit.go#L48

If you are running everything locally on the same machine, you'll need to either generate a cert for a hostname that resolves to 127.0.0.1, or you'll need to alter the code to be `ws://`, and set the hostname to `localhost`. `wss` is the `https` varient of `ws`.

It doesn't matter what interface you choose, so long as the code properly checks it and resolves it to 127.0.0.1. That is passed down to tell the other services what IP address to listen on.

Either you are I should create a bug that `wss` is hardcoded, and add an option for non-secure to be an option. ( at least until code to autogenerate a certificate for localhost is added )

The path from nginx back to mirrorfeed itself can be seen here in the example nginx conf: https://github.com/tmobile/stf_ios_support/blob/595ff792d2c70d112dbb2a84dd1074bf2f8c677e/server/nginx/nginx.conf#L79

You'll note that example configuration is only resolving that on port 443 ( `https` / `wss` )

You can't "visit" a `wss` websocket address directly and expect to see anything useful in the browser. I could perhaps alter the mirrorfeed program to allow that but it isn't setup that way.

You are correct that it is better to have ipv4 all the way and not have any ipv6 addresses mixed in; simply because I haven't tested ipv6 in any way and it is unlikely to work without additional changes. I thought I had made the IP resolution only choose ipv4 address and ignore the ipv6 ones but it looks like that is not the case. That also is another bug.

**Comment by Bull3time** [comment] 2020-01-03 11:40
Mirrorfeed seems happy, at least according to its logs

```
Opening incoming video: video_pipes/pipe_8000
Receiving incoming video
```

Yet I still can't get beyond `WebSocket connection to 'wss://10.1.1.200/frames/127.94.0.1/8000/x' failed: Unexpected response code: 502` no matter what I try with stf uris or hostnames or anything. Again corresponding nginx logs are
```
nginx_1                 | 2020/01/03 11:07:27 [error] 6#6: *30 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.144.1, server: _, request: "GET /frames/127.94.0.1/8000/x HTTP/1.1", upstream: "http://127.94.0.1:8000/echo/", host: "10.1.1.200"
nginx_1                 | 192.168.144.1 - - [03/Jan/2020:11:07:27 +0000] "GET /frames/127.94.0.1/8000/x HTTP/1.1" 502 150 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Safari/605.1.15"
```

Also strange is ffmpeg logs from the coordinator seem to indicate it is starting and stopping quite regularly yet `./log_view -proc ffmpeg` shows no logs whatsoever

```
INFO[1521] Starting: ffmpeg                              ops="[-f avfoundation -i iPhone -pixel_format bgr0 -f mjpeg -bsf:v mjpegadump -bsf:v mjpeg2jpeg -r 1 -vsync 2 -nostats pipe:1]" proc=ffmpeg type=proc_start uuid=XXXXXXX-XXXXXXXXXXXXXX
WARN[1521] Ended: ffmpeg                                 proc=ffmpeg type=proc_end uuid=XXXXXXX-XXXXXXXXXXXXXX
INFO[1531] Starting: ffmpeg                              ops="[-f avfoundation -i iPhone -pixel_format bgr0 -f mjpeg -bsf:v mjpegadump -bsf:v mjpeg2jpeg -r 1 -vsync 2 -nostats pipe:1]" proc=ffmpeg type=proc_start uuid=XXXXXXX-XXXXXXXXXXXXXX
WARN[1531] Ended: ffmpeg                                 proc=ffmpeg type=proc_end uuid=XXXXXXX-XXXXXXXXXXXXXX
```

I have self signed certificates and everything resolves fine, I tried a python websockets connection and it failed with `ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)`

I also thought maybe the nginx docker container was getting confused with localhost and thought it might have been trying to route inside its own container so I changed it all to be the external ip of the mac again no dice. Lastly I noticed one last 127 reference the 127.94 so I changed from lo0 in the config.json to the external interface and then it gets back to ipv6 and mirrorfeed throws this error 
```
Listening on fd7b:8e4a:f5b3:0:8c23:78e6:c0a6:8803:8000
Opening incoming video: video_pipes/pipe_8000
Receiving incoming video
2020/01/03 22:15:57 listen tcp: address fd7b:8e4a:f5b3:0:8c23:78e6:c0a6:8803:8000: too many colons in address
```
this one throws a 500 rather than a 502 though.

It seems like I am so close yet so far away, the video just doesn't want to work, if I start the coordinator without video openstf still has the same 500 error in console and the same nginx errors so video is definitely not happy with the frames endpoint for nginx and the logs from mirrorfeed seem to indicate it is starting fine (except with ipv6 as noted), i'm not really sure where the `192.168.144.1` address comes from though.

My final thoughts are try just an `stf local` run see if that works or to try and run nginx natively on my mac and remove any docker routing issues but keep everything else running inside the compose but that'll take some effort reworking the compose.

**Comment by nanoscopic** [comment] 2020-01-03 18:18
@Bull3time Re-reading your comments and details I think I perhaps understand what is going on now.

You are on the right track saying "perhaps I'll use `stf local` and run nginx natively". The reason why is because the way the code is setup currently, when you specify an network interface to listen on via `network_interface` in config.json, it is expected that that interface can be reached from Nginx for the video forwarding to work.

This is the reason that I specified `eth0` in the example config, because the local address you get from your router can be listened on, and then the docker container/nginx can also reach that IP address also. Eg: suppose you have a simple common switch you connect to and get a 192.168.1.56 address on it via DHCP. You can reach that address from within the docker container; which means that nginx can also reach it, so when you request the wss websocket address from a browser it will go through correctly.

If you change the `network_interface` config.json option to `lo0` or anything that resolves to 127.0.0.1; then mirrorfeed etc will bind to 127.0.0.1 on your machine. The 127.0.0.1 address inside of docker ( the one nginx has ) is a different interface. Localhost of the host machine running docker cannot be reached from within a docker container.

You can, perhaps, still use localhost / `lo0` if you do as you said and run everything outside of docker using stf local.

That is issue number 1.

Issue number 2 is that you are seeing ipv6 addresses anywhere. That is a glitch and unintended. I will look into that.

Issue number 3 is that you see ffmpeg restarting over and over. That should not happen. It should start once and start running when you start the coordinator. I've seen it fail for the following reasons:

1. It will fail if the terminal window used to run coordinator ( and in turn ffmpeg ) does not have permissions to get video. You can check for video permissions in Mac OS System Preference -> Security & Privacy -> Privacy tab -> Camera option ( on left ). Your terminal should appear in the list of apps that have access to "the Camera". You should have gotten prompted to grant that permission the first time you ran coordinator and it started ffmpeg. If that permission is not there, ffmpeg will not be able to pull video from your ios device.
2. It will fail if the named pipe in video_pipes does not exist or permissions for it are bad. This is unlikely to happen.
3. It will fail if the ios device gets into a weird state and generally doesn't pass video. So long as video shows through quicktime, this is not the case. If video fails to show in quicktime, you can try "Reset Media Services" on the ios device.
4. MacOS itself can sometimes get into a wonky state where it simply doesn't work and a reboot is required to fix it. I don't think this is the issue you are having; but be aware it can happen.
5. An incompatibility between the video sync method of the specific IOS version and ffmpeg options being passed. This has occurred in the past but should no longer be an issue. Just mentioning it here for completeness.
6. If mirrorfeed is not listening / have the named pipe open, then the named pipe will block and ffmpeg will appear to "do nothing". I think also it will restart automatically in this case every so often, because it gives up trying to write video into a blocked named pipe after a certain amount of time. When I've seen this happen, ffmpeg does not give reasonable error about it. So long as mirrorfeed is up and running pointed at the correct named pipe, this is not an issue. You can double check what pipe mirrorfeed has open, and which pipe ffmpeg is outputting to, by looking at `ps` or by looking at the log output of coordinator, specifically the `proc_start` log messages. The one for mirrorfeed contains the port. For ffmpeg the `proc_start` message is currently missing the port information; that is a bug and I will need to fix it. There is no simple way without a change to see which named pipe ffmpeg is being output too; because the output redirection is being done in golang and I failed to output the named pipe being used in the log.
7. Mirrorfeed cannot open the interface/port to listen on. This does seem to be happening for you in some of the logs you have shown above. Mirrorfeed uses the `network_interface` specified in config.json to decide which interface to listen on. The code that resolves the interface name to an IP address is here: https://github.com/tmobile/stf_ios_mirrorfeed/blob/master/mirrorfeed/mirrorfeed.go#L86 In your case it appears to be resolving to a ipv6 address. That is a bug and should be corrected. You can avoid this by specifing a `network_interface` that is ipv4 only for the moment. I will correct this problem.

Summary of issue 3:
I'm not quite sure what is happening in your case. All I can say certainly so far is that if ffmpeg is restarting repeatedly it isn't working. Hopefully the above details enable you to figure it out. Also, I will tweak mirrorfeed as said in point 7; which will remove the issue you are seeing with ipv6.

**Comment by nanoscopic** [comment] 2020-01-23 19:13
@DavidRayner There is documentation on the different components in the Wiki: https://github.com/tmobile/stf_ios_support/wiki Let me know if there is additional documentation or specific questions you have that are not explained by the information there.

In general, the provider and coordinator are the same thing. Starting the coordinator starts everything else. You don't need to start anything else manually on a provider machine besides the coordinator.

@Bull3time I looked into using localhost/en0 a bit more. Without rehashing everything, I'll simply say it won't work and we don't intend to support it. You must use a non-localhost interface to get provider and server working together the way the code is written.

The 'server' folder in the repo has been updated and now tested out fully on a blank VM in Virtualbox on Mac OS. Using such a VM running the server side of STF, and using a network interface that the Mac is connected to through Ethernet ( wireless could work too ), I have been able to get a full setup running on a single machine. ( my macbook )

I will add some additional overall instructions on doing that.

**Comment by Bull3time** [comment] 2020-01-29 07:50
Awesome look forward to the extra instructions.

**Comment by nanoscopic** [comment] 2020-02-12 21:24
The latest commits should address some of the issues seen above. I am successfully able to use en0 for example on the latest code. I think that localhost should work now also, but have yet to thoroughly test doing so.

The `init.sh` script has been cleaned up and setup improved a bunch. Node 12 is now used instead of Node 8. A bunch of random errors have been corrected to improve the startup process. Using within VPN has been tested a lot more and should work correctly now.

I'm losing track of what this issue is here for exactly; it has become too broad and open ended. If issues are still seen attempting to use `stf local` in combination with config.json like the following:
```
{
  ...
  "network": {
    "interface": "lo0"
  },
  ...
}

then please create a new ticket specifically about "support localhost/lo0 and `stf local`"

For other issues feel free to create issues specific to them too.

"Running IOS provider on the same machine with STF server" is proven and works currently in the following way:
1. Run STF server using `docker-compose` and the information in the repo server/ folder. This can be done either with docker-compose on Mac directly, or using a Linux VM running docker-compose.
2. Run coordinator normally and use a non-lo0 ethernet interface. ( such as en0 )

**Closed by nanoscopic** 2020-02-12 21:24 UTC
