### ISSUE TITLE
make fails

### ISSUE THREAD

**Issue by peak-load** [tmobile/stf_ios_support#50] opened 2020-06-02 06:34 UTC
```$ make
Use of uninitialized value $remote in substitution (s///) at ./check-versions.pl line 35.
Use of uninitialized value $date in numeric lt (<) at ./check-versions.pl line 39.
repos/ios_video_stream is out of date. Please git pull it. Then run `make cleanivs` them `make`
Use of uninitialized value $remote in substitution (s///) at ./check-versions.pl line 35.
Use of uninitialized value $date in numeric lt (<) at ./check-versions.pl line 39.
repos/wda is out of date. Please git pull it. Then run `make cleanwda` them `make`
Use of uninitialized value $remote in substitution (s///) at ./check-versions.pl line 35.
Use of uninitialized value $date in numeric lt (<) at ./check-versions.pl line 39.
repos/wdaproxy is out of date. Please git pull it. Then run `make cleanwdaproxy` then `make`
Use of uninitialized value $remote in substitution (s///) at ./check-versions.pl line 35.
Use of uninitialized value $date in numeric lt (<) at ./check-versions.pl line 39.
repos/h264_to_jpeg is out of date. Please git pull it. 
jq: error: Could not open file config.json: No such file or directory
cp config.json.example config.json
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C coordinator
go get
go get .
go build -o ../bin/coordinator .
git clone https://github.com/nanoscopic/ios_video_stream.git repos/ios_video_stream
Cloning into 'repos/ios_video_stream'...
remote: Enumerating objects: 1910, done.
remote: Counting objects: 100% (1910/1910), done.
remote: Compressing objects: 100% (649/649), done.
remote: Total 1910 (delta 1218), reused 1900 (delta 1208), pack-reused 0
Receiving objects: 100% (1910/1910), 22.48 MiB | 12.33 MiB/s, done.
Resolving deltas: 100% (1218/1218), done.
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C repos/ios_video_stream
go build -o ios_video_stream .
cp repos/ios_video_stream/ios_video_stream bin/ios_video_stream
git clone https://github.com/nanoscopic/ios_video_pull.git repos/ios_video_pull
Cloning into 'repos/ios_video_pull'...
remote: Enumerating objects: 31, done.
remote: Counting objects: 100% (31/31), done.
remote: Compressing objects: 100% (22/22), done.
remote: Total 31 (delta 14), reused 22 (delta 8), pack-reused 0
Receiving objects: 100% (31/31), 15.36 KiB | 7.68 MiB/s, done.
Resolving deltas: 100% (14/14), done.
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C repos/ios_video_pull
go build -o ios_video_pull .
cp repos/ios_video_pull/ios_video_pull bin/ios_video_pull
git clone https://github.com/tmobile/osx_ios_device_trigger.git repos/osx_ios_device_trigger
Cloning into 'repos/osx_ios_device_trigger'...
remote: Enumerating objects: 32, done.
remote: Counting objects: 100% (32/32), done.
remote: Compressing objects: 100% (15/15), done.
remote: Total 32 (delta 10), reused 27 (delta 9), pack-reused 0
Receiving objects: 100% (32/32), 10.80 KiB | 1.08 MiB/s, done.
Resolving deltas: 100% (10/10), done.
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C repos/osx_ios_device_trigger
xcodebuild -scheme osx_ios_device_trigger TARGET_BUILD_DIR="../../bin"
Command line invocation:
    /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -scheme osx_ios_device_trigger TARGET_BUILD_DIR=../../bin

Build settings from command line:
    TARGET_BUILD_DIR = ../../bin

note: Using new build system
note: Building targets in parallel
note: Planning build
note: Constructing build description
CompileC /Users/peak/Library/Developer/Xcode/DerivedData/osx_ios_device_trigger-fffxvcboqnqbusbiutqhxpamunos/Build/Intermediates.noindex/osx_ios_device_trigger.build/Debug/osx_ios_device_trigger.build/Objects-normal/x86_64/main.o /Users/peak/src/stf_ios_support/repos/osx_ios_device_trigger/osx_ios_device_trigger/main.cpp normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'osx_ios_device_trigger' from project 'osx_ios_device_trigger')
    cd /Users/peak/src/stf_ios_support/repos/osx_ios_device_trigger
    export LANG=en_US.US-ASCII
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x c++ -target x86_64-apple-macos10.14 -fmessage-length=229 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -fcolor-diagnostics -std=gnu++14 -stdlib=libc++ -fmodules -gmodules -fmodules-cache-path=/Users/peak/Library/Developer/Xcode/DerivedData/ModuleCache.noindex -fmodules-prune-interval=86400 -fmodules-prune-after=345600 -fbuild-session-file=/Users/peak/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/Session.modulevalidation -fmodules-validate-once-per-build-session -Wnon-modular-include-in-framework-module -Werror=non-modular-include-in-framework-module -Wno-trigraphs -fpascal-strings -O0 -fno-common -Wno-missing-field-initializers -Wno-missing-prototypes -Werror=return-type -Wdocumentation -Wunreachable-code -Werror=deprecated-objc-isa-usage -Werror=objc-root-class -Wno-non-virtual-dtor -Wno-overloaded-virtual -Wno-exit-time-destructors -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wconditional-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wno-float-conversion -Wnon-literal-null-conversion -Wobjc-literal-conversion -Wshorten-64-to-32 -Wno-newline-eof -Wno-c++11-extensions -DDEBUG=1 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -fasm-blocks -fstrict-aliasing -Wdeprecated-declarations -Winvalid-offsetof -g -fvisibility-inlines-hidden -Wno-sign-conversion -Winfinite-recursion -Wmove -Wcomma -Wblock-capture-autoreleasing -Wstrict-prototypes -Wrange-loop-analysis -Wno-semicolon-before-method-body -Wunguarded-availability -index-store-path /Users/peak/Library/Developer/Xcode/DerivedData/osx_ios_device_trigger-fffxvcboqnqbusbiutqhxpamunos/Index/DataStore -iquote /Users/peak/Library/Developer/Xcode/DerivedData/osx_ios_device_trigger-fffxvcboqnqbusbiutqhxpamunos/Build/Intermediates.noindex/osx_ios_device_trigger.build/Debug/osx_ios_device_trigger.build/osx_ios_device_trigger-generated-files.hmap -I/Users/peak/Library/Developer/Xcode/DerivedData/osx_ios_device_trigger-fffxvcboqnqbusbiutqhxpamunos/Build/Intermediates.noindex/osx_ios_device_trigger.build/Debug/osx_ios_device_trigger.build/osx_ios_device_trigger-own-target-headers.hmap -I/Users/peak/Library/Developer/Xcode/DerivedData/osx_ios_device_trigger-fffxvcboqnqbusbiutqhxpamunos/Build/Intermediates.noindex/osx_ios_device_trigger.build/Debug/osx_ios_device_trigger.build/osx_ios_device_trigger-all-target-headers.hmap -iquote /Users/peak/Library/Developer/Xcode/DerivedData/osx_ios_device_trigger-fffxvcboqnqbusbiutqhxpamunos/Build/Intermediates.noindex/osx_ios_device_trigger.build/Debug/osx_ios_device_trigger.build/osx_ios_device_trigger-project-headers.hmap -I/Users/peak/Library/Developer/Xcode/DerivedData/osx_ios_device_trigger-fffxvcboqnqbusbiutqhxpamunos/Build/Products/Debug/include -I/Users/peak/Library/Developer/Xcode/DerivedData/osx_ios_device_trigger-fffxvcboqnqbusbiutqhxpamunos/Build/Intermediates.noindex/osx_ios_device_trigger.build/Debug/osx_ios_device_trigger.build/DerivedSources-normal/x86_64 -I/Users/peak/Library/Developer/Xcode/DerivedData/osx_ios_device_trigger-fffxvcboqnqbusbiutqhxpamunos/Build/Intermediates.noindex/osx_ios_device_trigger.build/Debug/osx_ios_device_trigger.build/DerivedSources/x86_64 -I/Users/peak/Library/Developer/Xcode/DerivedData/osx_ios_device_trigger-fffxvcboqnqbusbiutqhxpamunos/Build/Intermediates.noindex/osx_ios_device_trigger.build/Debug/osx_ios_device_trigger.build/DerivedSources -F/Users/peak/Library/Developer/Xcode/DerivedData/osx_ios_device_trigger-fffxvcboqnqbusbiutqhxpamunos/Build/Products/Debug -MMD -MT dependencies -MF /Users/peak/Library/Developer/Xcode/DerivedData/osx_ios_device_trigger-fffxvcboqnqbusbiutqhxpamunos/Build/Intermediates.noindex/osx_ios_device_trigger.build/Debug/osx_ios_device_trigger.build/Objects-normal/x86_64/main.d --serialize-diagnostics /Users/peak/Library/Developer/Xcode/DerivedData/osx_ios_device_trigger-fffxvcboqnqbusbiutqhxpamunos/Build/Intermediates.noindex/osx_ios_device_trigger.build/Debug/osx_ios_device_trigger.build/Objects-normal/x86_64/main.dia -c /Users/peak/src/stf_ios_support/repos/osx_ios_device_trigger/osx_ios_device_trigger/main.cpp -o /Users/peak/Library/Developer/Xcode/DerivedData/osx_ios_device_trigger-fffxvcboqnqbusbiutqhxpamunos/Build/Intermediates.noindex/osx_ios_device_trigger.build/Debug/osx_ios_device_trigger.build/Objects-normal/x86_64/main.o
/Users/peak/src/stf_ios_support/repos/osx_ios_device_trigger/osx_ios_device_trigger/main.cpp:167:21: warning: variable 'uuid' is used uninitialized whenever 'if' condition is false [-Wsometimes-uninitialized]
                if( kr == kIOReturnSuccess && req.wLenDone > 0 ) {
                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/peak/src/stf_ios_support/repos/osx_ios_device_trigger/osx_ios_device_trigger/main.cpp:180:27: note: uninitialized use occurs here
        notify_interface( uuid, intfClass, intfSubClass, devVendor, devProduct );
                          ^~~~
/Users/peak/src/stf_ios_support/repos/osx_ios_device_trigger/osx_ios_device_trigger/main.cpp:167:17: note: remove the 'if' if its condition is always true
                if( kr == kIOReturnSuccess && req.wLenDone > 0 ) {
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/peak/src/stf_ios_support/repos/osx_ios_device_trigger/osx_ios_device_trigger/main.cpp:167:21: warning: variable 'uuid' is used uninitialized whenever '&&' condition is false [-Wsometimes-uninitialized]
                if( kr == kIOReturnSuccess && req.wLenDone > 0 ) {
                    ^~~~~~~~~~~~~~~~~~~~~~
/Users/peak/src/stf_ios_support/repos/osx_ios_device_trigger/osx_ios_device_trigger/main.cpp:180:27: note: uninitialized use occurs here
        notify_interface( uuid, intfClass, intfSubClass, devVendor, devProduct );
                          ^~~~
/Users/peak/src/stf_ios_support/repos/osx_ios_device_trigger/osx_ios_device_trigger/main.cpp:167:21: note: remove the '&&' if its condition is always true
                if( kr == kIOReturnSuccess && req.wLenDone > 0 ) {
                    ^~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/peak/src/stf_ios_support/repos/osx_ios_device_trigger/osx_ios_device_trigger/main.cpp:148:19: note: initialize the variable 'uuid' to silence this warning
        char *uuid;
                  ^
                   = nullptr
2 warnings generated.

Ld ../../bin/osx_ios_device_trigger normal x86_64 (in target 'osx_ios_device_trigger' from project 'osx_ios_device_trigger')
    cd /Users/peak/src/stf_ios_support/repos/osx_ios_device_trigger
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -target x86_64-apple-macos10.14 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -L/Users/peak/Library/Developer/Xcode/DerivedData/osx_ios_device_trigger-fffxvcboqnqbusbiutqhxpamunos/Build/Products/Debug -L/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/lib -F/Users/peak/Library/Developer/Xcode/DerivedData/osx_ios_device_trigger-fffxvcboqnqbusbiutqhxpamunos/Build/Products/Debug -filelist /Users/peak/Library/Developer/Xcode/DerivedData/osx_ios_device_trigger-fffxvcboqnqbusbiutqhxpamunos/Build/Intermediates.noindex/osx_ios_device_trigger.build/Debug/osx_ios_device_trigger.build/Objects-normal/x86_64/osx_ios_device_trigger.LinkFileList -Xlinker -object_path_lto -Xlinker /Users/peak/Library/Developer/Xcode/DerivedData/osx_ios_device_trigger-fffxvcboqnqbusbiutqhxpamunos/Build/Intermediates.noindex/osx_ios_device_trigger.build/Debug/osx_ios_device_trigger.build/Objects-normal/x86_64/osx_ios_device_trigger_lto.o -Xlinker -export_dynamic -Xlinker -no_deduplicate -stdlib=libc++ -lcurl -framework CoreFoundation -framework IOKit -Xlinker -dependency_info -Xlinker /Users/peak/Library/Developer/Xcode/DerivedData/osx_ios_device_trigger-fffxvcboqnqbusbiutqhxpamunos/Build/Intermediates.noindex/osx_ios_device_trigger.build/Debug/osx_ios_device_trigger.build/Objects-normal/x86_64/osx_ios_device_trigger_dependency_info.dat -o ../../bin/osx_ios_device_trigger
ld: warning: directory not found for option '-L/Users/peak/Library/Developer/Xcode/DerivedData/osx_ios_device_trigger-fffxvcboqnqbusbiutqhxpamunos/Build/Products/Debug'
ld: warning: directory not found for option '-F/Users/peak/Library/Developer/Xcode/DerivedData/osx_ios_device_trigger-fffxvcboqnqbusbiutqhxpamunos/Build/Products/Debug'

CodeSign ../../bin/osx_ios_device_trigger (in target 'osx_ios_device_trigger' from project 'osx_ios_device_trigger')
    cd /Users/peak/src/stf_ios_support/repos/osx_ios_device_trigger
    export CODESIGN_ALLOCATE=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/codesign_allocate
    
Signing Identity:     "-"

    /usr/bin/codesign --force --sign - --entitlements /Users/peak/Library/Developer/Xcode/DerivedData/osx_ios_device_trigger-fffxvcboqnqbusbiutqhxpamunos/Build/Intermediates.noindex/osx_ios_device_trigger.build/Debug/osx_ios_device_trigger.build/osx_ios_device_trigger.xcent --timestamp=none ../../bin/osx_ios_device_trigger

RegisterExecutionPolicyException ../../bin/osx_ios_device_trigger (in target 'osx_ios_device_trigger' from project 'osx_ios_device_trigger')
    cd /Users/peak/src/stf_ios_support/repos/osx_ios_device_trigger
    builtin-RegisterExecutionPolicyException ../../bin/osx_ios_device_trigger
note: Execution policy exception registration failed and was skipped: Error Domain=NSPOSIXErrorDomain Code=1 "Operation not permitted" (in target 'osx_ios_device_trigger' from project 'osx_ios_device_trigger')

** BUILD SUCCEEDED **
```

```
parse error: Invalid numeric literal at line 1, column 3
parse error: Invalid numeric literal at line 1, column 3
git clone  repos/WebDriverAgent --branch 
error: option `branch' requires a value
make: *** [repos/WebDriverAgent] Error 129
```

**Comment by nanoscopic** [comment] 2020-06-03 01:37
The initial script run by the Makefile uses the output of `./get-version-info.sh --unix --wdasource` to attempt to determine what version of the various repos there are. I'd have to see what the output of that command is to determine why / how the script is failing to process its output.

It looks like it may be working okay despite the output. It will initially say the repos need to be pulled as the first time `make` is run is when the repos get cloned. I'll look into fixing it to not dump out all the errors on the first run though. It is ugly and confusing.

The error about a missing config.json also makes sense as you need to create a config.json file initially. The instructions don't call this out clearly though, and the Makefile should be updated to handle that situations without all the errors as well. I will do this as well. ( update the Makefile and update the documentation to be clear that a config.json file should be created before running `make` )

The errors coming out of osx_ios_device_trigger look to be caused by the lack of config.json. Once you created one run `make` again and I believe it will build correctly.

It is strange to me that it attempts to codesign the device_trigger; that is not needed and does though seem to be default Xcode behavior. I'll investigate switching building of the device_trigger to gcc to avoid that.

Your second set of errors appears to be due to copying the config_example.json file to config.json ; that cannot be done and will cause errors. The reason why is because there are multiple examples within the example file, not a single one. You'll need to contruct a config.json file without comments. The comments included ( lines starting with // ) will break the parsing of config.json

**Comment by Kous92** [comment] 2020-06-04 12:05
@peak-load Your file config.json should be like that for example:
```
{
  "xcode_dev_team_id": "**********",
  "stf": {
    "ip": "127.0.0.1",
    "hostname": "localhost:7100"
  },
  "video": {
    "enabled": true,
    "use_vnc": false,
    "vnc_scale": 2,
    "vnc_password": "",
    "frame_rate": 10
  },
  "install": {
    "root_path": "./",
    "config_path": "./config.json"
  },
  "network": {
    "interface": "en1"
  }
}
```

From the config.json.example, create a config.json file on stf_ios_support and put the JSON data in the file without any comments. Take my model for example. NOTE: Don't forget to bring your Xcode Dev Team ID to make it work.

**Comment by peak-load** [comment] 2020-06-04 15:46
@Kous92  @nanoscopic  thanks

I also want report that current Makefile PATHs assumes that Node12 needs to be installed not from Homebrew, but from Nodejs package https://nodejs.org/en/download/

Otherwise brew path is not working, maybe add this to Readme.md

**Comment by peak-load** [comment] 2020-06-04 16:32
I was able to build all, OpenSTF server is running and now trying to ./run (according to the steps in Readme), getting exception:

```./run 
INFO[0000] Leftover device_trigger - Sending SIGTERM     proc=device_trigger type=proc_cleanup_kill
INFO[0000] Process start - device_trigger                binary=bin/osx_ios_device_trigger proc=device_trigger type=proc_start
INFO[0000] Process start - stf_ios_provider              binary=/usr/local/opt/node@12/bin/node client_hostname=MacBook-Pro.local client_ip=192.168.0.122 proc=stf_ios_provider server_hostname=localhost server_ip="127.0.0.1:7100" type=proc_start
INFO[0003] Device object created                         dev_ios_port=9240 dev_name= dev_uuid="***802E" type=devd_create vid_port=8000 vnc_port=5901 wda_port=8100
INFO[0003] Device connected                              dev_name= dev_uuid="***802E" type=dev_connect
panic: runtime error: index out of range [1] with length 0

goroutine 1 [running]:
github.com/nanoscopic/ujsonin/mod.Parse(0xc0003a6200, 0x0, 0x200, 0x200, 0x0, 0x0, 0x7)
	/Users/user/go/pkg/mod/github.com/nanoscopic/ujsonin@v1.6.0/mod/ujsonin.go:175 +0x1734
main.event_loop(0xc0000b0000, 0xc0000a72d0, 0xd, 0xc0000a21e0, 0xc000092360, 0xc0000a6eac, 0x3, 0xc0000a2180, 0xc000094e10, 0xc0000a6f20, ...)
	/Users/user/src/stf_ios_support/coordinator/coordinator.go:453 +0x2478
main.main()
	/Users/user/src/stf_ios_support/coordinator/coordinator.go:277 +0xf4b
E: 20-06-04 18:30:59 [62108]dangling 'REP' socket created at :325
E: 20-06-04 18:30:59 [62108]dangling 'PUB' socket created at :30
E: 20-06-04 18:30:59 [62108]dangling 'PULL' socket created at ?@?:163```

Please advice.

**Comment by nanoscopic** [comment] 2020-06-09 23:44
@peak-load I've only ever installed Node 12 through brew using the `init.sh` script. Do you not end up with a `/usr/local/opt/node@12` on your system after `brew install node@12` ?

The "index of of range [1]" error occurs when coordinator attempts to parse an empty block of JSON. This is a bug in that a better error message is not produced. I believe the version and line of code you are using that is generating this error is this one: https://github.com/tmobile/stf_ios_support/blob/77016502b7265c7677bc2dc132ca6a0afbe60ea7/coordinator/coordinator.go#L450

That call is parsing the result of `./bin/ios_video_pull -devices -json` You should run that command manually and see if you get output. If you do not get any output running that, that is the underlying issue.

There are also a bunch of changes committed yesterday, that, at least for me, fix a variety of overall issues. Before these commits there were still random issues that would present themselves on some systems. I'd advise to pull the updates, as well as the update to repos/wdaproxy. You should then re-run `init.sh` to install the latest needed packages as well before running `make` again.

Some updates are coming to the overall instructions on running a provider for the first time as well; I should have them committed and pushed sometime today. Essentially, to reliably start up a provider I'm now recommending that the video headers be cached using `./bin/coordinator -testVideo` before running the full coordinator. Details soon in README.

**Comment by nanoscopic** [comment] 2020-08-14 00:02
I believe the issues reported in this ticket have been resolved. Closing. Feel free to reopen and describe what the outstanding issue is if this is not true.

**Closed by nanoscopic** 2020-08-14 00:02 UTC
